### ISSUE TITLE
Need Bases to be "Safe Zones" 

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/WarMachine_Altis_DEV.Altis#17]
To prevent players from the opposing team of coming in with a jet/helo/tank and spawn camping the bases and all of the vehicles/people that spawn there, they need to be completely safe from the enemy. EUTW CTI has implemented this, any enemy round that enters the zone is deleted; might as well and do friendly rounds too, this way we can prevent TK at base.

The zone is about 1KM around the base and labeled on the map. 

Might need to adjust the safe zone depending on the mode selected. Bigger if it's full spectrum war (1km) and smaller if it's just infantry and the bases/fob/objectives are close together (100m).

**Comment by Gamer-Dad** [comment]
Believe I saw a text on the bottom left of the screen that said "You are now vulnerable" .

Progress!

Just need to show the player on the map where they're safe and not safe.

**Comment by Gamer-Dad** [comment]
Vehicles are still destroyed when in the base and attacked by enemy. Recommend any round that enters safe zone be deleted. Prevents TK and empty vehicles from being taken out by jets/helis.

Or you could add JET DLC defensive weapons + Radar and that will really limit their attacking capabilities.

**Comment by IvosHcz** [comment]
Soldiers playes+ai are invurnerable in the base. Need to find efficient solution for vehicles

**Comment by Gamer-Dad** [comment]
> 
> 
> Soldiers playes+ai are invurnerable in the base. Need to find efficient solution for vehicles

Modes like KOTH, EUTW CTI, simply delete any bullet/projectile (enemy/friendly) when inside a base zone.

**Comment by IvosHcz** [comment]
Done. Vehicles on the base and planes are protected. FOB vehicles don't. Solved by "EH GetIn" (efficient)
