### ISSUE TITLE
Autostart for Dedicated Servers

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/WarMachine_Altis_DEV.Altis#25]
The mission generator is not ideal for public dedicated servers, need overhaul on how the mission launches; random players should never have access to the mission generator or admin menu from the action menu.

**Comment by Gamer-Dad** [comment]
IvosH pushed an edit, but the mission generator is still available in the action menu as well as the admin option.

**Comment by IvosHcz** [comment]
Updated, can be set in the lobby

**Comment by Gamer-Dad** [comment]
That works, thanks.
