### ISSUE TITLE
Parameter Edit: Random selection

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/WarMachine_Altis_DEV.Altis#34]
Could we also include a "random" option to some of the params, the one below being a prime example of where it's needed.

`class asp1 //Mission type
	{
		title = "   - Mission type               What types of the vehicles will be avliable - AO size"; 
		texts[] = 
		{
			"Infantry mission - Infantry, light vehicles - AO small",
			"Combined ground forces - Infantry, light vehicles, armors, transport helicopter - AO medium",
			"Full spectrum warfare - Infantry, light vehicles, armors, transport helicopter, gunship, jet - AO large"
		};
		values[] = {0,1,2};
		default = 2;
	};	`

**Comment by IvosHcz** [comment]
Done
